version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch_
    environment:
      - "discovery.type=single-node"
    #expose:
    #  - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: kibana_
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    container_name: logstash_
    ports:
      - "5044:5044"
